  <div class="span5  shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_http.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/todoist.png" 
                   data-original-title="Add a Task : Adds a Todoist Task ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/twitter.png" 
                   data-original-title="New Status Update : Any message this Channel receives will trigger a new Twitter Status Update ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/1bd58e53-127e-5de8-d266-000034b47745.jpg" alt="">
            daisuke          </div>
          
        </div>
        <div>
          <label>            
            dai          </label>
          <div class="share-bip-description">              
            <p>To triggered by hatena web hook.</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5 offset1 shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/flow.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Key/Value Change Forwarder : Given a key,value pair, continues graph processing if the value has changed ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/phantomjs.png" 
                   data-original-title="Screen Shot a Web Page : Takes a screen shot of a given URL in a browser ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/crypto.png" 
                   data-original-title="Generates a MD5 Hash : Generates a MD5 Hash of the supplied content ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/html.png" 
                   data-original-title="W3C Validate : Validates HTML with the W3C Validation Service, exporting the results ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/email.png" 
                   data-original-title="Send an Email : Use to forward email messages to a chosen recipient (requires recipient verification) ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Generate a Payload : Generates a Payload that can be processed by a Trigger Bip ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            Site Validation Check - With Screenshot          </label>
          <div class="share-bip-description">              
            <p>Checks a generator URL periodically, sending W3C validation message changes to a target email account</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5  shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_smtp.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/email.png" 
                   data-original-title="Send an Email : Use to forward email messages to a chosen recipient (requires recipient verification) ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Filter messages by a search pattern : Conditionally forwards or discards messages matching certain search patterns ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/twilio.png" 
                   data-original-title="Send an SMS message : Sends a new outgoing SMS Message. If you are sending SMS while your Twilio account is in Trial mode, the "To" phone number must be verified with Twilio. ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            producthunt          </label>
          <div class="share-bip-description">              
            <p>Forwards Emails from ProductHunt, SMS's you when your favorite App is mentioned.  Sign up to ProductHunt with the email address generated from this Bip</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5 offset1 shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_http.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/email.png" 
                   data-original-title="Send an Email : Use to forward email messages to a chosen recipient (requires recipient verification) ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/06fbe77a-dae1-4a1b-8b26-2acc26e7f250.jpg" alt="">
            blockjon          </div>
          
        </div>
        <div>
          <label>            
            my-first-bip          </label>
          <div class="share-bip-description">              
            <p>some description here</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5  shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/twitter.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/hipchat.png" 
                   data-original-title="Send a message to a room : Send a message to a room ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/twitter.png" 
                   data-original-title="Get Mentions : Forwards the details of any Tweet where your username is mentioned ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            Twitter Mentions to a HipChat Room          </label>
          <div class="share-bip-description">              
            <p>Any time you're mentioned in a Tweet, sends a message to one of your HipChat rooms</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5 offset1 shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/flow.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Key/Value Change Forwarder : Given a key,value pair, continues graph processing if the value has changed ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/syndication.png" 
                   data-original-title="Create A Feed : Creates an syndication from content you receive from Bips ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/embedly.png" 
                   data-original-title="Extract Page : The Extract endpoint is designed to provide users with important information from each link including the article text, keywords, related links, and even video embeds. ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/crypto.png" 
                   data-original-title="Generates a MD5 Hash : Generates a MD5 Hash of the supplied content ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Generate a Payload : Generates a Payload that can be processed by a Trigger Bip ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            URL Payload > RSS Content Syndication          </label>
          <div class="share-bip-description">              
            <p>With a Generator Channel that has a URL as a payload, tracks changes to the URL's extracted content and creates a Syndication (Requires Embedly API)</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5  shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/syndication.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/time.png" 
                   data-original-title="Calculate a Time : Calculates a time from a simple natural language expression, eg: "in 2 days" ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/trello.png" 
                   data-original-title="Create A Card : Adds a Card to an existing List ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/flow.png" 
                   data-original-title="Filter messages by a search pattern : Conditionally forwards or discards messages matching certain search patterns ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/syndication.png" 
                   data-original-title="Subscribe to a Feed : Subscribes to an RSS/ATOM/RDF Feed ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            Trello Card from Filtered RSS          </label>
          <div class="share-bip-description">              
            <p>Adds a Trello Card when a filtered entity appears via RSS, due within a certain time</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5 offset1 shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_http.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/phantomjs.png" 
                   data-original-title="Screen Shot a Web Page : Takes a screen shot of a given URL in a browser ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/email.png" 
                   data-original-title="Send an Email : Use to forward email messages to a chosen recipient (requires recipient verification) ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            marco          </div>
          
        </div>
        <div>
          <label>            
            screenshot to email          </label>
          <div class="share-bip-description">              
            <p>Sends a web page screen shot to your inbox with a simple webhook</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5  shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_http.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/hipchat.png" 
                   data-original-title="Send a message to a room : Send a message to a room ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/github.png" 
                   data-original-title="Create an Issue : Create an Issue for the target repository ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            m          </div>
          
        </div>
        <div>
          <label>            
            Public Hook to Github Issue          </label>
          <div class="share-bip-description">              
            <p>Posts a new issue to Github and Hipchat room with a WebHook</p>             
          </div>
        </div>        
      </div>
    </div>
  <div class="span5 offset1 shared-bip-container">
      <div class="row">
        <div class="bip-summary-container" style="width: 110px;
          margin-left: 40px;
          float: left;">
          
        <div class="bip-summary middle">
          <img class="tooltipped" data-placement="top" title="" src="https://bip.io/static/img/channels/32/color/bip_http.png">
          <div class="shared-bip-list">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/http.png" 
                   data-original-title="HTTP Request : Makes a HTTP Request, exporting the response body or generating a file ">          
                          <img class="mini tooltipped" data-placement="top" title="" 
                   src="https://bip.io/static/img/channels/32/color/google.png" 
                   data-original-title="Create a File on Google Drive : Uploads any present file to Google drive ">          
              
          </div>
          </div>                         
          
          <div>
            via <img class="user-avatar mini" src="https://bip.io/static/img/cdn/av/95f78228-2da4-44bb-b2b0-a12ff50ae48c.jpg" alt="">
            m          </div>
          
        </div>
        <div>
          <label>            
            Fetch To Google Drive          </label>
          <div class="share-bip-description">              
            <p>Sends to Google Drive any files fetched with this hook with the ?url={file url} parameter</p>             
          </div>
        </div>        
      </div>
    </div>
