<script data-main="/static/js/docs-main" src="/static/js/vendor/require/require.js"></script>

<div class="row">
	<div class="span12" >

    <h1 class="middle" style="padding: 20px 0;">
      Rapidly Integrate Any Supported Service
    </h2>

    <?php echo $this->partial($this->partialPath, array('domainPfx' => $this->domainPfx)); ?>

    <div class="container">
      <div class="row">
        <div class="span12 middle">
          <!-- a id="toggle-all-pods" class="fade in btn btn-primary">SEE ALL AVAILABLE SERVICES</a -->
          <a id="suggest-pod" class="fade in btn btn-primary" target="_blank" href="https://bip.uservoice.com/forums/281363-general">Something Missing? Let Us Know!</a>
        </div>
      </div>
    </div>
  </div>
</div>