
    <!-- MAP SCRIPTS -->
      <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
      <script type="text/javascript">
          // When the window has finished loading create our google map below
          google.maps.event.addDomListener(window, 'load', init);

          function init() {
              // Basic options for a simple Google Map
              // For more options see: https://developers.google.com/maps/documentation/javascript/reference#MapOptions
            var scMap = new google.maps.LatLng(40.742856, -73.9917342);
              var mapOptions = {
                  // How zoomed in you want the map to start at (always required)
                  zoom: 15,

                  scrollwheel: false,

                  // The latitude and longitude to center the map (always required)
                  center: new google.maps.LatLng(40.742856, -73.9917342), // New York

                  // How you would like to style the map.
                  // This is where you would paste any style found on Snazzy Maps.
                  styles: [ {
                  featureType:'water',
                  stylers:[{color:'#c7defc'},{visibility:'on'}] },
                  {   featureType:'landscape',    stylers:[{color:'#f2f2f2'}] },
                  {   featureType:'road',   stylers:[{saturation:-100},{lightness:45}]  },
                  {   featureType:'road.highway',   stylers:[{visibility:'simplified'}] },
                  {   featureType:'road.arterial',
                      elementType:'labels.icon',
                      stylers:[{visibility:'off'}]  },
                      {   featureType:'administrative',
                      elementType:'labels.text.fill',
                      stylers:[{color:'#444444'}] },
                      {   featureType:'transit',
                      stylers:[{visibility:'off'}]  },
                      {   featureType:'poi',    stylers:[{visibility:'off'}]  }]
                    };

              // Get the HTML DOM element that will contain your map
              // We are using a div with id="map" seen below in the <body>
              var mapElement = document.getElementById('map');

              // Create the Google Map using out element and options defined above
              var map = new google.maps.Map(mapElement, mapOptions);

          var marker = new google.maps.Marker({
                position: scMap,
                map: map,
                title:"WoT.io, inc",

     });
     //Content structure of info Window for the Markers
          var contentString = $('<div class="marker-info-win">'+
            '<div class="marker-inner-win"><span class="info-content">'+
            '<h1 class="marker-heading">New Marker</h1>'+
            'This is a new marker infoWindow'+
            '</span>'+
            '</div></div>');

            //Create an infoWindow
            var infowindow = new google.maps.InfoWindow();

            //set the content of infoWindow
            infowindow.setContent(contentString[0]);

            //add click event listener to marker which will open infoWindow
            google.maps.event.addListener(marker, 'click', function() {
                infowindow.open(map,marker); // click on marker opens info window
            });
          }

      </script>

    <div class="row middle" style="font-size: 2em;line-height: 1.5em;">
      <div class="span4">
        <h1 style="font-size: 3em;"><i class="icon-home"></i></h1>
        WoT.io, inc<br/>
        30 W 24th Street, Floor 6<br/>
        New York, NY 10010<br/><br/>
        <a href="tel:+12126753904">+1 212-675-3904</a><br/><br/>
        <a href="mailto:hello@bip.io">hello@bip.io</a>
      </div>
      <div class="span8">
      <div id="map" style="width: 100%;
        height: 425px;

        overflow: hidden;
        transform: translateZ(0px);
        background-color: rgb(229, 227, 223);
        "></div>
      </div>
    </div>

