<script data-main="/static/js/signin" src="/static/js/vendor/require/require.js"></script>
<div class="row">
    <div class="span12">
<h2>Opt-in Notice</h2>
<p>
The bip.io Privacy Policy was updated on April 23, 2015.
<p>
If your first use of the bip.io service (the “Service”) occurred prior to April 23, 2015 (the “Effective Date”), the updated bip.io Privacy Policy (the “Updated Privacy Policy”), available at <a target="_blank" href="/privacy">https://bip.io/privacy</a>, does not retroactively apply to any information that we have collected about you prior to the Effective Date, unless and until you opt-in to the Updated Privacy Policy by checking the box below.
</p>
<p>
The Updated Privacy Policy contains the following changes to the July 28, 2012 version of the bip.io privacy policy (the “Previous Privacy Policy”):
</p>
<h3>External Data Storage Sites</h3>
<p>
Under the Previous Privacy Policy, your personal information is stored on servers provided by third party hosting vendor Linode.  Under the Updated Privacy Policy, your personal information will generally be stored on servers hosted by third party service providers with whom we have contracted.
</p>
<h3>Proper Use and Storage of Your Personal Information</h3>

<p>
The Updated Privacy Policy makes clear that your personal information will be stored and maintained by us for as long as we, in our sole discretion, believe is necessary or appropriate (a) to carry out the purpose(s) and the use(s) for which such information was collected or (b) to comply with applicable laws, contracts, or other rules or regulations.
</p>
<h3>Sharing Your Personal Information</h3>

<p>
Under the Previous Privacy Policy, we do not sell your e-mail address or contact information to, or share such information with, any third parties, except law enforcement and other government officials as required to enforce law and intellectual property rights.  Under the Updated Privacy Policy, we will not sell your personal information to, or share or trade your personal information with, any third parties except in the following circumstances:
<ul>
	<li>Sharing with your consent</li>
	<li>Sharing with our affiliates</li>
	<li>Sharing with authorized third party service providers</li>
	<li>Sharing in connection with business transfers</li>
	<li>Sharing as required by law or for the protection of rights</li>
	<li>Access to Your Personal Information</li>
</ul>
</p>

<p>
The Updated Privacy Policy tells you how and where to conveniently access and manage your personal information, including personal information in your bip.io account, and how to notify us about errors.
</p>

<h3>Do Not Track</h3>
<p>
The Updated Privacy Policy explains that we do not support Do Not Track with respect to your usage of the Service.
</p>

<h3>Changes to the bip.io Privacy Policy</h3>
<p>
Under the Previous Privacy Policy, any modifications to the Previous Privacy Policy are effective thirty (30) days after the modifications are posted on the Service.  Under the Updated Privacy Policy, any modifications to the Updated Privacy Policy are effective immediately upon posting the modifications on the Service.
</p>

<p>
 By checking this box, I acknowledge that I have read, understand and consent to the changes to the Previous Privacy Policy, including those changes concerning the sharing of my personal information, and that I am opting-in to the Updated Privacy Policy, available at <a target="_blank" href="/privacy">https://bip.io/privacy</a>
</p>
    </div>
    <div class="label label-success pull-right">
      <input style="margin: 0;" type="checkbox" id="tos-accept">&nbsp;&nbsp;I Accept
     </div>
</div>