<style type="text/css">
html, body {
    height: 100%;
}
#page-body {
    height: 30%;
}
</style>

<div id="container" class="row middle">
		<img src="/static/img/bot_timeout.png" style="width: 256px;height: 256px;">
    <h1>
    	<small>Oops! The Server Timed Out</small>
    	<br/>
    	<br/>
    	<a href="/dash" class="btn btn-success"><i class="icon-exclamation-sign"></i> TRY AGAIN</a>
    </h1>
</div>
